config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :comments do
      resources :likes, only: [:create]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'topics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  has_many :likes, :dependent => :destroy
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :topic
  belongs_to :comment, counter_cache: :like
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :comments
  is_impressionable
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def root
    render html: "なろうのオススメへようこそ！！"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @topic = Topic.where(:id => params[:topic_id]).first
    @comments = @topic.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @topic = Topic.where(:id => params[:topic_id]).first
    @comment = @topic.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @topic = Topic.where(:id => params[:topic_id]).first
    @comment = @topic.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントありがとうございます！！！' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to topic_path(@topic), alert: '※空欄の場合コメントできません' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_path(id: @comment.topic_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @topic = Topic.where(:id => params[:topic_id]).first
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to topic_path(@topic), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:topic_id, :content, :name, :like)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(topic_id: params[:topic_id], comment_id: params[:comment_id])
    @topic = Topic.where(:id => params[:topic_id]).first
    @comment = Comment.where(:id => params[:comment_id]).first
    if @like.save
      flash[:notice] = "Like was removed."
    else
      flash[:error] = "Like couldn't be created. Try again."
    end
    respond_to do |format|
       format.js { }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topic = Topic.new
    @topics = Topic.order("id desc")
    @topics = Topic.page(params[:page]).per(10).order("id desc")
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.where(:id => params[:id]).first
    impressionist(@topic, nil, unique: [:session_hash])
    @comments = @topic.comments.all.order("created_at")
    @comment = @topic.comments.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: '新しい質問が作成されました！ありがとうございます！' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { redirect_to topics_path, alert: '※空欄の場合トピック作成できません' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:content, :like, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = @page_title if @page_title
  end

  def page_description
    description = @page_description
  end

  def default_meta_tags
    {
      site: 'なろう廃人のすすめ',
      title: page_title,
      reverse: false,
      charset: 'utf-8',
      description: '小説家になろうのオススメ小説を教えあう共有サイトです。',
      keywords: '小説家になろう, なろう, なろう小説, おすすめ, オススメ',
      canonical: request.original_url,
      separator: ':',
      icon: [
        # { href: image_url('favicon.ico') },
        # { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'なろう廃人のすすめ',
        title: page_title,
        description: '小説家になろうのオススメ小説を教えあう共有サイトです。',
        type: 'website',
        url: request.original_url,
        # image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: '@ツイッターのアカウント名',
      }
    }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for [@topic, @comment] do |f|
      = f.label :content
      = f.text_field :content
      = f.label :like
      = f.number_field :like
      = f.submit "質問作成", class: "btn btn-primary"

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form', comment: @comment
= link_to 'Show', @comment
|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%p#notice= notice
%h1 Comments
%table
  %thead
    %tr
      %th Content
      %th Like
      %th{:colspan => "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.content
        %td= comment.like
        %td= link_to 'Show', topic_comment_path(@topic, comment)
        %td= link_to 'Edit', edit_topic_comment_path(@topic, comment)
        %td= link_to 'Destroy', topic_comment_path(@topic, comment), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_topic_comment_path

app/views/comments/new.html.haml
%h1 New Comment
= render 'form', comment: @comment
= link_to 'Back', topic_comments_path

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong Topic:
  = @comment.topic
%p
  %strong Content:
  = @comment.content
%p
  %strong Like:
  = @comment.like
= link_to 'Edit', edit_topic_comment_path(@comment)
|
= link_to 'Back', topic_comments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = analytics_init if Rails.env.production?
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
  %body
    :javascript
      window._pt_lt = new Date().getTime();
      window._pt_sp_2 = [];
      _pt_sp_2.push('setAccount,31ba411d');
      var _protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
      (function() {
          var atag = document.createElement('script'); atag.type = 'text/javascript'; atag.async = true;
          atag.src = _protocol + 'js.ptengine.jp/pta.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(atag, s);
      })();
    = yield

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { topic: @topic,  comment: @comment, like: @like}) %>")

app/views/topics/_comment-like.html.haml
= button_to topic_comment_likes_path(topic, comment, like),  id: "like-button", class: "fa fa-heart-o float-right like-button btn", remote: true do
  %span{"class"=>"comment-like-number"}
    -if comment.like.present?
      #{comment.like}
    -else
      0

app/views/topics/_form.html.haml
= form_with(model: topic, local: true) do |form|
  - if topic.errors.any?
    #error_explanation
      %h2
        = pluralize(topic.errors.count, "error")
        prohibited this topic from being saved:
      %ul
        - topic.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :content
    = form.text_field :content
  .field
    = form.label :like
    = form.number_field :like
  .actions
    = form.submit

app/views/topics/edit.html.haml
%h1 Editing Topic
= render 'form', topic: @topic
= link_to 'Show', @topic
|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
= image_tag("/images/header.png", width: '375', alt: "なろう廃人のすすめ", class: "d-block d-md-none mx-auto")
= image_tag("/images/header-pc.png", alt: "なろう廃人のすすめ", class: "d-none d-md-block img-fluid pb-2")
.container.pt-2{:style => "background-color:#e0ffff;"}
  .row.mx-1.mb-2
    .card
      .font-weight-bold
        人気記事
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "1:軽く読める短編でおすすめのやつを教えてください。", "https://narou-osusume.com/topics/29", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "2:勘違い系のおすすめが知りたいです。", "https://narou-osusume.com/topics/1", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "3:あなたが1つだけ誰かにオススメするとしたらどの小説にしますか？", "https://narou-osusume.com/topics/33", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "4:書籍化したなろうで明らかに良くなったやつとかあるの？", "https://narou-osusume.com/topics/5", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "5:異世界転生もののテンプレって実際どんなのだろ？", "https://narou-osusume.com/topics/6", target: "_blank"
      %hr{style: "margin: 0px;"}
  .row
    #notice= notice
    #alert= alert
  - @topics.each do |topic|
    = link_to(topic_path(topic), target: "_blank") do
      .card.mx-auto.shadow
        .card-body.py-1
          .row
            .font-weight-bold{:style => "font-size:18px; color:#283593;"}
              = topic.content
          .row
            .small.text-muted.p-1.pt-2{:style => "font-size:11px"}
              %span{"class"=>"comment-count"}【
              .fa.fa-comments-o.topic-comment-icon
              %span{"class"=>"comment-count"}（#{topic.comments.count}）】
              -# 名前表示がごちゃっとするから一旦コメントアウト
              -# - if topic.name.present?
              -#   %span{"class"=>"topic-create-user-name"}【
              -#   .fa.fa-pencil.topic-name
              -#   %span{"class"=>"topic-create-user-name"} #{topic.name}】
              = topic.created_at.strftime("%Y/%m/%d/ %H:%M")
              【#{topic.impressionist_count} PV】
  .mt-2
    = paginate @topics

  .row.m-3
    / 切り替えボタンの設定
    %button.btn.comment-button{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
      = fa_icon 'pencil 2x'
    / モーダルの設定
    #myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
          .modal-header
            #exampleModalLabel.modal-title
              .h3.mt-2
                新しい話題を作る
            %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
              .pt-3{"aria-hidden" => "true"} ×
          .modal-body
            .row
              .mx-auto
                = form_for(@topic) do |f|
                  .mx-auto
                    = f.label :name
                    = f.text_field :name, value:"なろう廃人さん", placeholder:"名前", required: "required"
                  = f.text_area :content, placeholder:"廃人さんたちに訊きたいことを書いてください！", class: "mx-auto mt-2 d-block modal-topic-text", required: "required"
                  .m-3
                    = f.submit "質問作成", class: "btn btn-primary px-5 mx-auto d-block"

app/views/topics/new.html.haml
/
  <haml_loud> render &#39;form&#39;, topic: @topic </haml_loud>

  <haml_loud> link_to &#39;Back&#39;, topics_path </haml_loud>
%h1 新しい質問を立ち上げる
.row
  .col-md-6.col-md-offset-3
    = form_for(@topic) do |f|
      = f.label :name
      = f.text_field :name, :value=>"なろう廃人さん", :placeholder=>'名前'
      = f.label :content
      = f.text_area :content, :placeholder=>'廃人たちに訊きたい質問を書いてください！'
      = f.label :like
      = f.number_field :like
      = f.submit "質問作成", class: "btn btn-primary"

app/views/topics/show.html.haml
- @page_title = @topic.content
- @page_description = @topic.comments
= link_to image_tag("/images/header.png", width: '375', alt: "なろう廃人のすすめ", class: "d-block d-md-none mx-auto"), topics_path
= link_to image_tag("/images/header-pc.png", alt: "なろう廃人のすすめ", class: "d-none d-md-block img-fluid pb-2"), topics_path
.container.pt-2{:style => "background-color:#e0ffff;"}
  .row.mx-1.mb-2
    .card
      .font-weight-bold
        人気記事
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "1:軽く読める短編でおすすめのやつを教えてください。", "https://narou-osusume.com/topics/29", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "2:勘違い系のおすすめが知りたいです。", "https://narou-osusume.com/topics/1", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "3:あなたが1つだけ誰かにオススメするとしたらどの小説にしますか？", "https://narou-osusume.com/topics/33", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "4:書籍化したなろうで明らかに良くなったやつとかあるの？", "https://narou-osusume.com/topics/5", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "5:異世界転生もののテンプレって実際どんなのだろ？", "https://narou-osusume.com/topics/6", target: "_blank"
      %hr{style: "margin: 0px;"}
  .row.mb-2
    #notice= notice
    #alert= alert
    .card.mt-2.mb-2.w-100
      .card-body.py-1
        .font-weight-bold{:style => "font-size:18px; color:#283593;"}
          = @topic.content
          .small.text-muted.p-1.pt-2{:style => "font-size:11px"}
            %span{"class"=>"comment-count"}【
            .fa.fa-comments-o.topic-comment-icon
            %span{"class"=>"comment-count"}（#{@topic.comments.count}）】
            - if @topic.name
              %span{"class"=>"topic-create-user-name"}【
              .fa.fa-pencil.topic-name
              %span{"class"=>"topic-create-user-name"} #{@topic.name}】
            = @topic.created_at.strftime("%Y/%m/%d/ %H:%M")
            【#{@topic.impressionist_count} PV】
  -# トピックの持つコメントを全て表示
  - @comments.each_with_index do |comment, id|
    .row
      .card.mx-2.w-100.shadow
        .card-body.pl-2.pt-3.pb-2{:style => "min-height:100px;"}
          .row.pl-3.pb-2.small.text-muted
            %span{"class"=>"comment-index-number"} #{id+1}
            ：
            -# 名前ある時だけ、アイコンと名前を表示
            -if comment.name.present?
              -# .fa.fa-pencil.mr-1{:style => "color:grey"}
              #{comment.name}
            = comment.created_at.strftime("%Y/%m/%d/ %H:%M:%S")
          .font-weight-bold.pb-4
            = simple_format(comment.content,:style => "font-size:17px; line-height:160%;")
          = render :partial => "comment-like", :locals => { topic: @topic,  comment: comment, like: @like }
          -# 返信ボタン
          .fa.fa-reply.float-right.reply-button.btn{"data-target" => "#myReplyModal", "data-toggle" => "modal"}
  -# コメント下のフォーム
  .row
    .mx-auto.mt-4
      = form_for [@topic, @comment] do |f|
        = f.label :名前
        -# 後でcontent > name に変えて名前を登録できるようにする
        = f.text_field :name, value:"なろう廃人さん", placeholder:"名前", required: "required"
        = f.text_area :content, :placeholder=>'コメントお願いします！', class: "mt-2 d-block under-comment-text", required: "required"
        .m-3
          = f.submit "コメントする", class: "btn btn-primary px-5 mx-auto d-block"

  -# 人気記事をハードコーディング
  .row.mx-1
    .card
      .font-weight-bold
        人気記事
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "1:軽く読める短編でおすすめのやつを教えてください。", "https://narou-osusume.com/topics/29", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "2:勘違い系のおすすめが知りたいです。", "https://narou-osusume.com/topics/1", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "3:あなたが1つだけ誰かにオススメするとしたらどの小説にしますか？", "https://narou-osusume.com/topics/33", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "4:書籍化したなろうで明らかに良くなったやつとかあるの？", "https://narou-osusume.com/topics/5", target: "_blank"
      %hr{style: "margin: 0px;"}
      .card-body{style: "padding-top: 0px; padding-bottom: 0px; bordercolor:#e0e2e6;"}
        = link_to "5:異世界転生もののテンプレって実際どんなのだろ？", "https://narou-osusume.com/topics/6", target: "_blank"
      %hr{style: "margin: 0px;"}

  .row.m-3
    / 切り替えボタンの設定
    %button.btn.comment-button{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
      = fa_icon 'pencil 2x'
    / モーダルの設定
    #myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
          .modal-header
            #exampleModalLabel.modal-title #{@topic.content}
            %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
              .pt-3{"aria-hidden" => "true"} ×
          .modal-body
            .row
              .mx-auto
                = form_for [@topic, @comment] do |f|
                  = f.label :名前
                  = f.text_field :name, value:"なろう廃人さん", placeholder:"名前", required: "required"
                  = f.text_area :content, placeholder:'コメントありがとうございます！', class: "mx-auto mt-2 d-block modal-text", required: "required"
                  .m-3
                    = f.submit "コメントする", class: "btn btn-primary px-5 mx-auto d-block"
  -# 返信用のモーダル
  .row.m-3
    / 切り替えボタンの設定
    %button.btn.comment-button{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
      = fa_icon 'pencil 2x'
    / モーダルの設定
    #myReplyModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
          .modal-header
            #exampleModalLabel.modal-title #{@topic.content}
            %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
              .pt-3{"aria-hidden" => "true"} ×
          .modal-body
            .row
              .mx-auto
                = form_for [@topic, @comment] do |f|
                  = f.label :名前
                  -# 後でcontent > name に変えて名前を登録できるようにする
                  = f.text_field :name, value:"なろう廃人さん", placeholder:"名前", required: "required"
                  = f.text_area :content, placeholder:"コメントありがとうございます！", class: "aaaa mx-auto mt-2 d-block modal-text reply-modal-text", required: "required"
                  .m-3
                    = f.submit "コメントする", class: "btn btn-primary px-5 mx-auto d-block"